### ISSUE TITLE
Drop PHPUnit 4/5 fallback

### ISSUE THREAD

**Issue by Zeromax** [byjg/php-swagger-test#13]
Is it possible to drop the phpunit4 fallback?
```php
if (!class_exists('\PHPUnit\Framework\TestCase')) {
    class_alias('\PHPUnit_Framework_TestCase', '\PHPUnit\Framework\TestCase');
}
```

I think there is no reason to keep this. PHPUnit 4 and 5 are no longer supported. see https://phpunit.de/

It would improve the auto completion for phpstorm a lot ;)

**Comment by byjg** [comment]
Hi.

I also hate this fallback for PHPUnit, but since we support PHP5.6 I have to maintain this fallback *OR* drop the support for PHP 5.6 also;

Unfortunately I cannot drop the support for PHP 5.6 at this moment, but I am open for discuss alternatives to solve this problem. If you have some idea will be welcome. 

Major Version | PHP Compatibility | Initial Release | Support
-- | -- | -- | --
PHPUnit 8 | PHP 7.2, PHP 7.3, PHP 7.4 | February 1, 2019 | Support ends on February 5, 2021
PHPUnit 7 | PHP 7.1, PHP 7.2, PHP 7.3 | February 2, 2018 | Support ends on February 7, 2020
PHPUnit 6 | PHP 7.0, PHP 7.1, PHP 7.2 | February 3, 2017 | Support ends on February 1, 2019
PHPUnit 5 | PHP 5.6, PHP 7.0, PHP 7.1 | October 2, 2015 | Support ended on February 2, 2018

**Comment by Zeromax** [comment]
Hi,

thanks for your answer. Ok, I get your point.
mybe it ist possible to drop phpunit 4 only and increase to phpunit `5.4`.

Cause this is the version when they introduced the `\PHPUnit\Framework\TestCase` class.
https://phpunit.de/manual/5.4/en/writing-tests-for-phpunit.html

less then `5.3` needs this fallback:
https://phpunit.de/manual/5.3/en/writing-tests-for-phpunit.html

Is this a possibility? So we can keep php 5.6 and remove the fallback.

**Comment by byjg** [comment]
Yeah, I see PHPUnit 5.* offers support to PHP 5.6, 7.0 and 7.1. The support for PHPUnit 5.3, 5.4 is no longer necessary. 

I created a branch issue-13 for that.

**Comment by Zeromax** [comment]
Perfect. Thank you.

**Comment by byjg** [comment]
Added the Release "1.2.4"
